[package]
name = "bevy_basic_template"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7"
bevy-inspector-egui = "0.11"
iyes_loopless = "0.5.1"
leafwing-input-manager = "0.3"

[workspace]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3
